In [ ]:
# import libraries
import pandas as pd
import numpy as np

In [ ]:
# open csv file
df=pd.read_csv('real_estate.csv')

In [ ]:

df

,price,Area,bathroom,bedroom,location
0,PKR2 Crore,4 Marla,-,-,"Eden Gardens, Faisalabad, Punjab"
1,PKR8 Crore,13 Marla,5,4,"Canal Road, Faisalabad, Punjab"
2,PKR15 Crore,1 Kanal,6,5,"Canal Road, Faisalabad, Punjab"
3,PKR5.5 Crore,14.5 Marla,5,5,"Canal Road, Faisalabad, Punjab"
4,PKR8.5 Crore,11 Marla,-,-,"Canal Road, Faisalabad, Punjab"
...,...,...,...,...,...
745,PKR12.5 Crore,1 Kanal,6,5,"DHA Defence, Islamabad, Islamabad Capital"
746,PKR11.22 Crore,1 Kanal,6,5,"DHA Defence, Islamabad, Islamabad Capital"
747,PKR28 Crore,1 Kanal,6,6,"F-8, Islamabad, Islamabad Capital"
748,PKR10.5 Crore,1 Kanal,6,5,"DHA Defence, Islamabad, Islamabad Capital"
749,PKR35 Crore,2 Kanal,6,6,"F-8, Islamabad, Islamabad Capital"

In [ ]:
# check null and datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750 entries, 0 to 749
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   price     750 non-null    object
 1   Area      750 non-null    object
 2   bathroom  750 non-null    object
 3   bedroom   750 non-null    object
 4   location  750 non-null    object
dtypes: object(5)
memory usage: 29.4+ KB

In [ ]:
# check duplicates
df.duplicated().sum()

np.int64(100)

In [ ]:
df

,price,Area,bathroom,bedroom,location
0,PKR2 Crore,4 Marla,-,-,"Eden Gardens, Faisalabad, Punjab"
1,PKR8 Crore,13 Marla,5,4,"Canal Road, Faisalabad, Punjab"
2,PKR15 Crore,1 Kanal,6,5,"Canal Road, Faisalabad, Punjab"
3,PKR5.5 Crore,14.5 Marla,5,5,"Canal Road, Faisalabad, Punjab"
4,PKR8.5 Crore,11 Marla,-,-,"Canal Road, Faisalabad, Punjab"
...,...,...,...,...,...
745,PKR12.5 Crore,1 Kanal,6,5,"DHA Defence, Islamabad, Islamabad Capital"
746,PKR11.22 Crore,1 Kanal,6,5,"DHA Defence, Islamabad, Islamabad Capital"
747,PKR28 Crore,1 Kanal,6,6,"F-8, Islamabad, Islamabad Capital"
748,PKR10.5 Crore,1 Kanal,6,5,"DHA Defence, Islamabad, Islamabad Capital"
749,PKR35 Crore,2 Kanal,6,6,"F-8, Islamabad, Islamabad Capital"

In [ ]:
df.loc[232]

price                          PKR2.35 Crore
Area                                 5 Marla
bathroom                                   4
bedroom                                    3
location    Eden Gardens, Faisalabad, Punjab
Name: 232, dtype: object

In [ ]:
df.shape

(750, 5)

### extract city

In [ ]:
# define a function to extract the city
def city(x):
  city=x.split(',')[1]
  return city

### extract location

In [ ]:
# define a function to extract the location
def location(x):
  location=x.split(',')[0]
  return location

### remove PKR from price

In [ ]:
def price_value(x):
  price=x.split('PKR')[1]
  return price

### Apply these functions

In [ ]:
df['city']=df['location'].apply(city)
# on running it, it will show error as there are some rows that donot have ',' in location
# check them

In [ ]:
# check the rows that donot have ',' in the location
df[df['location'].apply(lambda x: ',' not in str(x))]['location']

336    For Sale
338    For Sale
339    For Sale
340    For Sale
394    For Sale
396    For Sale
397    For Sale
398    For Sale
417    For Sale
418    For Sale
419    For Sale
420    For Sale
471    For Sale
472    For Sale
473    For Sale
474    For Sale
492    For Sale
Name: location, dtype: object

In [ ]:
# remove them
df = df[df['location'] != 'For Sale']
df = df.reset_index(drop=True)

In [ ]:
# now apply
df['city']=df['location'].apply(city)

In [ ]:
df['location']=df['location'].apply(location)

In [ ]:
df['price']=df['price'].apply(price_value)

In [ ]:
df

           price        Area bathroom bedroom      location         city
0        2 Crore     4 Marla        -       -  Eden Gardens   Faisalabad
1        8 Crore    13 Marla        5       4    Canal Road   Faisalabad
2       15 Crore     1 Kanal        6       5    Canal Road   Faisalabad
3      5.5 Crore  14.5 Marla        5       5    Canal Road   Faisalabad
4      8.5 Crore    11 Marla        -       -    Canal Road   Faisalabad
..           ...         ...      ...     ...           ...          ...
728   12.5 Crore     1 Kanal        6       5   DHA Defence    Islamabad
729  11.22 Crore     1 Kanal        6       5   DHA Defence    Islamabad
730     28 Crore     1 Kanal        6       6           F-8    Islamabad
731   10.5 Crore     1 Kanal        6       5   DHA Defence    Islamabad
732     35 Crore     2 Kanal        6       6           F-8    Islamabad

[733 rows x 6 columns]

### now convert lakh, crore and arab in numeric price

In [ ]:
df['price'].apply(lambda x: 'Crore' in str(x)).sum()

np.int64(728)

In [ ]:
# check the rows that donot contain price in Crore
df[df['price'].apply(lambda x: 'Crore' not in str(x))]

         price       Area bathroom bedroom      location        city
308    55 Lakh    5 Marla        2       2  Raiwind Road      Lahore
324    75 Lakh    2 Marla        2       2  Qadri Colony      Lahore
352    68 Lakh    3 Marla        2       2   Multan Road      Lahore
354    65 Lakh    3 Marla        2       2  Jubilee Town      Lahore
678  1.89 Arab  3.7 Kanal        6       8           F-6   Islamabad

In [ ]:
# create a function to convert
def price_int(x):
  price=x.split(' ')
  if price[1] == 'Lakh':
    price_numeric=float(price[0]) * 100000
  elif price[1] == 'Crore':
    price_numeric=float(price[0]) * 10000000
  else:
    price_numeric=float(price[0]) * 1000000000
  return price_numeric

In [ ]:
df['price']=df['price'].apply(price_int)

In [ ]:
df

           price        Area bathroom bedroom      location         city
0     20000000.0     4 Marla        -       -  Eden Gardens   Faisalabad
1     80000000.0    13 Marla        5       4    Canal Road   Faisalabad
2    150000000.0     1 Kanal        6       5    Canal Road   Faisalabad
3     55000000.0  14.5 Marla        5       5    Canal Road   Faisalabad
4     85000000.0    11 Marla        -       -    Canal Road   Faisalabad
..           ...         ...      ...     ...           ...          ...
728  125000000.0     1 Kanal        6       5   DHA Defence    Islamabad
729  112200000.0     1 Kanal        6       5   DHA Defence    Islamabad
730  280000000.0     1 Kanal        6       6           F-8    Islamabad
731  105000000.0     1 Kanal        6       5   DHA Defence    Islamabad
732  350000000.0     2 Kanal        6       6           F-8    Islamabad

[733 rows x 6 columns]

### convert Kanal to Marla

In [ ]:
# first check that all is all the data related to kanal and marla
first=df['Area'].apply(lambda x: 'Kanal' not in str(x)).sum()
second=df['Area'].apply(lambda x: 'Marla' not in str(x)).sum()
print(first+second)

733

In [ ]:
# define a function to convert kanal to marla
def Kanal_to_marla(x):
  value_unit=x.split(' ')
  value=value_unit[0]
  unit=value_unit[1]
  if unit == 'Kanal':
    new_value = float(value) * 20
  else:
    new_value = float(value)
  return new_value

In [ ]:
df['Area']=df['Area'].apply(Kanal_to_marla)

In [ ]:
df

           price  Area bathroom bedroom      location         city
0     20000000.0   4.0        -       -  Eden Gardens   Faisalabad
1     80000000.0  13.0        5       4    Canal Road   Faisalabad
2    150000000.0  20.0        6       5    Canal Road   Faisalabad
3     55000000.0  14.5        5       5    Canal Road   Faisalabad
4     85000000.0  11.0        -       -    Canal Road   Faisalabad
..           ...   ...      ...     ...           ...          ...
728  125000000.0  20.0        6       5   DHA Defence    Islamabad
729  112200000.0  20.0        6       5   DHA Defence    Islamabad
730  280000000.0  20.0        6       6           F-8    Islamabad
731  105000000.0  20.0        6       5   DHA Defence    Islamabad
732  350000000.0  40.0        6       6           F-8    Islamabad

[733 rows x 6 columns]

In [ ]:
df['Area'].loc[5]

np.float64(5.0)

### Replace - with nan (empty)

In [ ]:
df['bathroom'].replace('-',np.nan,inplace=True)
df['bedroom'].replace('-',np.nan,inplace=True)

/tmp/ipykernel_2296/1083306788.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bathroom'].replace('-',np.nan,inplace=True)
/tmp/ipykernel_2296/1083306788.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bedroom'].replace('-',np.nan,inplace=True)

In [ ]:
df

           price  Area bathroom bedroom      location         city
0     20000000.0   4.0      NaN     NaN  Eden Gardens   Faisalabad
1     80000000.0  13.0        5       4    Canal Road   Faisalabad
2    150000000.0  20.0        6       5    Canal Road   Faisalabad
3     55000000.0  14.5        5       5    Canal Road   Faisalabad
4     85000000.0  11.0      NaN     NaN    Canal Road   Faisalabad
..           ...   ...      ...     ...           ...          ...
728  125000000.0  20.0        6       5   DHA Defence    Islamabad
729  112200000.0  20.0        6       5   DHA Defence    Islamabad
730  280000000.0  20.0        6       6           F-8    Islamabad
731  105000000.0  20.0        6       5   DHA Defence    Islamabad
732  350000000.0  40.0        6       6           F-8    Islamabad

[733 rows x 6 columns]

### Calculate Area in sq feet

In [ ]:
# define a function to calculate area in sq.feet
def area_sqft(x):
  value=x*272.25
  return value

In [ ]:
df['area_sqft']=df['Area'].apply(area_sqft)

In [ ]:
df

           price  Area bathroom bedroom      location         city  area_sqft
0     20000000.0   4.0      NaN     NaN  Eden Gardens   Faisalabad   1089.000
1     80000000.0  13.0        5       4    Canal Road   Faisalabad   3539.250
2    150000000.0  20.0        6       5    Canal Road   Faisalabad   5445.000
3     55000000.0  14.5        5       5    Canal Road   Faisalabad   3947.625
4     85000000.0  11.0      NaN     NaN    Canal Road   Faisalabad   2994.750
..           ...   ...      ...     ...           ...          ...        ...
728  125000000.0  20.0        6       5   DHA Defence    Islamabad   5445.000
729  112200000.0  20.0        6       5   DHA Defence    Islamabad   5445.000
730  280000000.0  20.0        6       6           F-8    Islamabad   5445.000
731  105000000.0  20.0        6       5   DHA Defence    Islamabad   5445.000
732  350000000.0  40.0        6       6           F-8    Islamabad  10890.000

[733 rows x 7 columns]

### Rename Area to area_marla

In [ ]:
df.rename(columns={'Area': 'area_marla'}, inplace=True)

### Calculate price per marla

In [ ]:
df['price_per_marla'] = df['price'] / df['area_marla']

In [ ]:
df

,price,area_marla,bathroom,bedroom,location,city,area_sqft,price_per_marla
0,20000000.0,4.0,NaN,NaN,Eden Gardens,Faisalabad,1089.000,5.000000e+06
1,80000000.0,13.0,5,4,Canal Road,Faisalabad,3539.250,6.153846e+06
2,150000000.0,20.0,6,5,Canal Road,Faisalabad,5445.000,7.500000e+06
3,55000000.0,14.5,5,5,Canal Road,Faisalabad,3947.625,3.793103e+06
4,85000000.0,11.0,NaN,NaN,Canal Road,Faisalabad,2994.750,7.727273e+06
...,...,...,...,...,...,...,...,...
728,125000000.0,20.0,6,5,DHA Defence,Islamabad,5445.000,6.250000e+06
729,112200000.0,20.0,6,5,DHA Defence,Islamabad,5445.000,5.610000e+06
730,280000000.0,20.0,6,6,F-8,Islamabad,5445.000,1.400000e+07
731,105000000.0,20.0,6,5,DHA Defence,Islamabad,5445.000,5.250000e+06
732,350000000.0,40.0,6,6,F-8,Islamabad,10890.000,8.750000e+06

In [ ]:
df

,price,area_marla,bathroom,bedroom,location,city,area_sqft,price_per_marla
0,20000000.0,4.0,NaN,NaN,Eden Gardens,Faisalabad,1089.000,5.000000e+06
1,80000000.0,13.0,5,4,Canal Road,Faisalabad,3539.250,6.153846e+06
2,150000000.0,20.0,6,5,Canal Road,Faisalabad,5445.000,7.500000e+06
3,55000000.0,14.5,5,5,Canal Road,Faisalabad,3947.625,3.793103e+06
4,85000000.0,11.0,NaN,NaN,Canal Road,Faisalabad,2994.750,7.727273e+06
...,...,...,...,...,...,...,...,...
728,125000000.0,20.0,6,5,DHA Defence,Islamabad,5445.000,6.250000e+06
729,112200000.0,20.0,6,5,DHA Defence,Islamabad,5445.000,5.610000e+06
730,280000000.0,20.0,6,6,F-8,Islamabad,5445.000,1.400000e+07
731,105000000.0,20.0,6,5,DHA Defence,Islamabad,5445.000,5.250000e+06
732,350000000.0,40.0,6,6,F-8,Islamabad,10890.000,8.750000e+06

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 733 entries, 0 to 732
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   price            733 non-null    float64
 1   area_marla       733 non-null    float64
 2   bathroom         678 non-null    object
 3   bedroom          686 non-null    object
 4   location         733 non-null    object
 5   city             733 non-null    object
 6   area_sqft        733 non-null    float64
 7   price_per_marla  733 non-null    float64
dtypes: float64(4), object(4)
memory usage: 45.9+ KB

### Change the data type of bathroom and bedroom (object to int)

In [ ]:
df['bedroom']=df['bedroom'].astype('Int64')

In [ ]:
df['bathroom']=df['bathroom'].astype('Int64')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 733 entries, 0 to 732
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   price            733 non-null    float64
 1   area_marla       733 non-null    float64
 2   bathroom         678 non-null    Int64
 3   bedroom          686 non-null    Int64
 4   location         733 non-null    object
 5   city             733 non-null    object
 6   area_sqft        733 non-null    float64
 7   price_per_marla  733 non-null    float64
dtypes: Int64(2), float64(4), object(2)
memory usage: 47.4+ KB

### check duplicates

In [ ]:

df.duplicated().sum()

np.int64(92)

In [ ]:
df

,price,area_marla,bathroom,bedroom,location,city,area_sqft,price_per_marla
0,20000000.0,4.0,<NA>,<NA>,Eden Gardens,Faisalabad,1089.000,5.000000e+06
1,80000000.0,13.0,5,4,Canal Road,Faisalabad,3539.250,6.153846e+06
2,150000000.0,20.0,6,5,Canal Road,Faisalabad,5445.000,7.500000e+06
3,55000000.0,14.5,5,5,Canal Road,Faisalabad,3947.625,3.793103e+06
4,85000000.0,11.0,<NA>,<NA>,Canal Road,Faisalabad,2994.750,7.727273e+06
...,...,...,...,...,...,...,...,...
728,125000000.0,20.0,6,5,DHA Defence,Islamabad,5445.000,6.250000e+06
729,112200000.0,20.0,6,5,DHA Defence,Islamabad,5445.000,5.610000e+06
730,280000000.0,20.0,6,6,F-8,Islamabad,5445.000,1.400000e+07
731,105000000.0,20.0,6,5,DHA Defence,Islamabad,5445.000,5.250000e+06
732,350000000.0,40.0,6,6,F-8,Islamabad,10890.000,8.750000e+06

In [ ]:
df = df.drop_duplicates(keep='first').reset_index(drop=True)

In [ ]:
df

,price,area_marla,bathroom,bedroom,location,city,area_sqft,price_per_marla
0,20000000.0,4.0,<NA>,<NA>,Eden Gardens,Faisalabad,1089.000,5.000000e+06
1,80000000.0,13.0,5,4,Canal Road,Faisalabad,3539.250,6.153846e+06
2,150000000.0,20.0,6,5,Canal Road,Faisalabad,5445.000,7.500000e+06
3,55000000.0,14.5,5,5,Canal Road,Faisalabad,3947.625,3.793103e+06
4,85000000.0,11.0,<NA>,<NA>,Canal Road,Faisalabad,2994.750,7.727273e+06
...,...,...,...,...,...,...,...,...
636,125000000.0,20.0,6,5,DHA Defence,Islamabad,5445.000,6.250000e+06
637,112200000.0,20.0,6,5,DHA Defence,Islamabad,5445.000,5.610000e+06
638,280000000.0,20.0,6,6,F-8,Islamabad,5445.000,1.400000e+07
639,105000000.0,20.0,6,5,DHA Defence,Islamabad,5445.000,5.250000e+06
640,350000000.0,40.0,6,6,F-8,Islamabad,10890.000,8.750000e+06

In [ ]:
df['city'].value_counts()

city
Islamabad     233
Faisalabad    215
Lahore        193
Name: count, dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

### check empty

In [ ]:
df.isna().sum()

price               0
area_marla          0
bathroom           40
bedroom            32
location            0
city                0
area_sqft           0
price_per_marla     0
dtype: int64

In [ ]:
# Some property listings do not provide bedroom or bathroom information.
# These missing values were retained as NaN rather than removing the
# corresponding property records, because the remaining information
# (price, area, location, etc.) is still useful for analysis.

### check the numerice values must be greater then 0

In [ ]:
df[df['area_marla']<=0]

Empty DataFrame
Columns: [price, area_marla, bathroom, bedroom, location, city, area_sqft, price_per_marla]
Index: []

In [ ]:
df[df['price']<=0]

Empty DataFrame
Columns: [price, area_marla, bathroom, bedroom, location, city, area_sqft, price_per_marla]
Index: []

In [ ]:
df[df['bathroom']<=0]

Empty DataFrame
Columns: [price, area_marla, bathroom, bedroom, location, city, area_sqft, price_per_marla]
Index: []

In [ ]:
df[df['bedroom']<=0]

Empty DataFrame
Columns: [price, area_marla, bathroom, bedroom, location, city, area_sqft, price_per_marla]
Index: []

In [ ]:
df[df['area_marla']<=0]

Empty DataFrame
Columns: [price, area_marla, bathroom, bedroom, location, city, area_sqft, price_per_marla]
Index: []

In [ ]:
df.sample(5)

,price,area_marla,bathroom,bedroom,location,city,area_sqft,price_per_marla
480,149000000.0,30.0,<NA>,<NA>,DHA Defence,Islamabad,8167.50,4.966667e+06
598,58500000.0,4.4,5,3,D-12,Islamabad,1197.90,1.329545e+07
121,41000000.0,7.0,5,4,Eden Valley,Faisalabad,1905.75,5.857143e+06
385,55500000.0,10.0,6,5,Paragon City,Lahore,2722.50,5.550000e+06
542,42500000.0,8.0,6,5,Bahria Town,Islamabad,2178.00,5.312500e+06

In [ ]:
df.to_csv('clean_real_estate.csv')